version: '3'
services:
  web:
    build: .
    volumes:
      - ./ci:/var/www/html/
    ports:
      - "8000:80"
    networks:
      - bisstox_dev_network

networks:
  bisstox_dev_network:
    external: true
