version: '3'
services:
  web:
    build: .
    volumes:
      - ./ci:/var/www/html/
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data:
